//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SKETCH.RC
//
#define IDR_MAINFRAME                   3
#define IDCANCEL2                       3
#define IDC_CLOSE                       4
#define IDCANCEL3                       4
#define ID_LIB_SETTINGS                 7
#define IDR_COLORFRAME                  13
#define IDD_ABOUTBOX                    100
#define IDD_NEW                         101
#define IDD_SPLASH                      102
#define IDB_SPLASH                      103
#define IDD_SLIDER                      103
#define IDB_SLIDER                      104
#define IDC_THUMBS                      105
#define IDC_VCR                         106
#define IDC_FLIP                        107
#define IDC_SCRUB                       108
#define IDD_THUMBS                      109
#define IDW_SLIDER                      110
#define IDD_OPTIONS                     111
#define IDD_AVIINDLG                    112
#define IDD_TOOLDLG                     113
#define IDD_FILEOPENPREVIEW             115
#define IDD_COLORDIALOG                 116
#define ID_VCR_EXIT                     117
#define ID_VCR_HOME                     118
#define ID_VCR_BACK                     119
#define ID_VCR_STOP                     120
#define ID_VCR_PLAY                     121
#define ID_VCR_END                      122
#define ID_VCR_BSTEP                    123
#define ID_VCR_FSTEP                    124
#define ID_VCR_LOOP                     125
#define IDD_GRIDDLG                     126
#define ID_RATE_UP                      127
#define ID_RATE_DOWN                    128
#define IDD_OLD_NEW                     129
#define IDD_DETAILS                     130
#define IDR_CAPDIALOG                   131
#define IDD_PROGRESS                    132
#define IDD_RECORDING                   133
#define IDD_ZTOOLBOX                    135
#define IDD_PALETTE2                    136
#define IDD_BRUSHES                     137
#define IDB_BRUSHES                     138
#define IDD_DENSITY                     140
#define IDB_DENSITY                     141
#define IDB_TOOLBOX                     142
#define IDB_PALETTE                     143
#define IDD_CELLOVER                    144
#define IDD_AVI                         145
#define IDD_LEVEL                       146
#define IDD_LEVEL_PRO                   147
#define IDD_GIF                         148
#define IDD_MOVIE                       149
#define IDC_VERSION                     150
#define IDC_TXTLOG                      151
#define IDB_NEWTOOLBOX                  153
#define IDD_INITIAL_DISC                154
#define IDD_INITIAL                     155
#define IDD_CELL                        156
#define IDC_MAGCUR                      158
#define IDC_HANDCUR                     159
#define IDC_PENCIL                      160
#define IDC_TRACE                       161
#define IDC_BRUSH                       162
#define IDC_FILL                        163
#define IDC_TFILL                       166
#define IDC_TBRUSH                      167
#define IDC_EPENCIL                     170
#define IDC_ETRACE                      171
#define IDC_EBRUSH                      172
#define IDC_EFILL                       173
#define IDC_TEFILL                      176
#define IDC_TEBRUSH                     177
#define IDC_LPENCIL                     180
#define IDC_LTRACE                      181
#define IDC_LBRUSH                      182
#define IDC_LFILL                       183
#define IDC_TLFILL                      186
#define IDC_TLBRUSH                     187
#define IDC_LEPENCIL                    190
#define IDC_LETRACE                     191
#define IDC_LEBRUSH                     192
#define IDC_LEFILL                      193
#define IDC_TLEFILL                     196
#define IDC_TLEBRUSH                    197
#define IDC_MAGCUR1                     198
#define IDC_CAM_SELECT                  199
#define IDC_NS_CUR                      200
#define IDC_EW_CUR                      201
#define IDC_SCALE_CUR                   202
#define IDC_ROTATE_CUR                  203
#define IDC_BLUR_CUR                    204
#define IDC_ALPHA_CUR                   205
#define IDC_CENTER_CUR                  210
#define IDC_NSEW_CUR                    211
#define IDD_DEMO                        212
#define IDD_FXSPECK                     213
#define IDC_EYEDROP1                    215
#define IDC_EYEDROP2                    216
#define IDC_EYEDROP3                    217
#define IDD_NUCAP_DIALOG                220
#define IDD_DV_DIALOG                   221
#define IDD_FXMATTE                     222
#define IDD_EXTEDIT                     223
#define IDD_EXTERNAL                    224
#define IDD_PAL_EXT_MOD                 225
#define IDD_PAL_UNUSED                  226
#define IDD_TOOL_RAD                    230
#define IDD_TOOL_RADDEN                 231
#define IDD_TOOL_FILL                   232
#define IDD_TOOL_ZOOM                   233
#define IDD_TOOL_SELECT                 234
#define IDD_EXT_EMPTY                   235
#define IDD_ASSOC_EXE                   236
#define IDD_NOSAVE                      237
#define IDD_SEL_PAL                     238
#define IDD_TOOL_NUPEN                  239
#define IDD_LIB_SAVE                    240
#define IDD_LIB_SETTINGS                241
#define IDD_FROM_AVI                    242
#define IDB_SELECTTOOL                  299
#define IDB_PENCILTOOL                  300
#define IDB_TRACETOOL                   301
#define IDB_BRUSHTOOL                   302
#define IDB_FILLTOOL                    303
#define IDB_ZOOMTOOL                    304
#define IDB_HANDTOOL                    305
#define IDB_EYEDROPTOOL                 306
#define IDB_ERASERTOOL                  307
#define IDB_MAT_FILL_TOOL               308
#define IDB_MAT_BRSH_TOOL               309
#define IDB_WANDTOOL                    310
#define IDD_KEEP_LINK2                  311
#define IDD_REGISTER                    312
#define IDD_CAMERA                      313
#define IDD_CAMDIALOG                   314
#define IDD_GROUP                       315
#define IDD_PEG                         316
#define IDD_KEY_TYPE                    317
#define IDD_SCENE_PROP                  318
#define IDD_GOTO                        319
#define IDD_SCANNEW                     320
#define IDD_VIEWLOG                     321
#define IDD_PRINTING                    322
#define IDD_GRAB_DLG                    323
#define IDD_LAYER                       324
#define IDD_LAYERX                      325
#define IDD_SCANSKEW                    326
#define IDC_TBRUSHP                     327
#define IDC_LERASER                     328
#define IDC_ZERASER                     329
#define IDD_COLOR_KEY                   330
#define IDD_KEEP_LINK1                  331
#define IDD_EXPIRE                      332
#define IDD_EXPIRED2                    333
#define IDD_EXPIRESOON                  334
#define IDD_TEMPSOON                    335
#define IDD_TEMPNOW                     336
#define IDD_REGISTER_DISC               337
#define IDD_EXPIRESOON1                 340
#define IDB_CAM_SELECT_TOOL             350
#define IDB_CAM_PAN_TOOL                351
#define IDB_CAM_ZOOM_TOOL               352
#define IDB_CAM_ROTATE_TOOL             353
#define IDB_CAM_BLUR_TOOL               354
#define IDB_CAM_ALPHA_TOOL              355
#define IDB_CAM_DALLKEYS                356
#define IDB_CAM_DTHISKEY                357
#define IDB_CAM_NEXTKEY                 358
#define IDB_CAM_PREVKEY                 359
#define IDB_CAM_PEG_TOOL                360
#define IDB_ZCAM_NSEW                   361
#define IDB_ZCAM_DLG                    362
#define IDB_ZCAM_SCRUB                  363
#define IDD_CAP_OPTIONS                 368
#define IDD_NUSCAN_DIALOGK              369
#define IDD_COLOR_KIND                  370
#define IDD_GRAD                        371
#define IDC_GRAD1                       372
#define IDC_GRAD2                       373
#define IDC_GRAD                        374
#define IDD_PRODUCTS                    375
#define IDD_LIGHTBOX                    377
#define IDD_NEW_COLOR_KEY               378
#define IDD_PUBLISH                     379
#define IDD_EXIST_SINGLE                380
#define IDD_LOSE_ALPHA                  381
#define IDD_CUST_TOOLBAR                382
#define IDC_MYWAND                      383
#define IDC_MYWAND2                     384
#define IDD_REGISTER_IT                 385
#define IDD_OTHER                       386
#define IDD_OURS                        387
#define IDD_TEXTURE                     388
#define IDC_MYCROSS                     389
#define IDC_MYLASSO                     390
#define IDD_PAL_SHARED                  391
#define IDD_PAL_LINKED                  392
#define IDD_PAL_MISSING                 393
#define IDD_PAL_DIFF                    394
#define IDD_PAL_NO_TEXTURE              395
#define IDD_LIPSYNC                     399
#define IDD_SUBPALETTE                  400
#define IDD_LIGHTBOX_PAINT              401
#define IDD_MYLIB                       402
#define IDB_COL_THIN                    450
#define IDB_COL_WIDE                    451
#define IDB_EYE_NOPEN                   452
#define IDB_EYE_OPEN                    453
#define IDB_EAR_NOPEN                   454
#define IDB_EAR_OPEN                    455
#define IDB_COL_INFO                    456
#define IDB_INITBMP                     500
#define IDB_INITBMP_DISC                501
#define IDD_SOUND                       502
#define IDD_FILEIMPORT                  503
#define IDD_FRAME                       504
#define IDD_EXPORT                      505
#define IDD_DGXWARNING                  506
#define IDI_ICON1                       507
#define IDD_REGFEEDBACK                 508
#define IDI_ICON2                       509
#define IDD_FXFILL                      510
#define IDD_REPLACE                     511
#define IDD_IDWARNING                   512
#define IDD_CUT_CELLS                   513
#define IDD_DEL_CELLS                   514
#define IDD_FXFLIP                      517
#define IDD_COLOR_DLG                   520
#define IDD_SNDTRACK_DLG                521
#define IDD_APPENDED_SND                522
#define IDD_COPIES_IN_USE               523
#define IDD_CRASHED                     524
#define IDD_REPAIRED                    525
#define IDD_VID_RECORD                  526
#define IDD_PUCK                        527
#define IDD_ZOOMER                      528
#define IDD_EXPORT_CAM                  529
#define IDD_IMPORT_CAM                  530
#define IDD_EMBED_OPEN                  531
#define IDD_EMBED_SAVE                  532
#define IDD_EMBED_ALREADY               533
#define IDD_EXPORT_EMBED                534
#define IDD_EMBED_OPT                   535
#define IDD_FRAME_NUMBER                536
#define COLOR_ALPHAACCEL                998
#define COLOR_ALPHA                     999
#define IDC_CAP_ROT180                  1000
#define IDC_CAP_USENBRS                 1001
#define IDC_SHOWBG                      1002
#define IDC_PEGMAXDEPTH                 1003
#define IDC_GRID                        1004
#define IDC_PEGMINDENSITY               1005
#define IDC_PENCILMAXDENSITY            1006
#define IDC_VID_DEVICES                 1006
#define IDC_PENCILMINDENSITY            1007
#define IDC_AUD_DEVICES                 1007
#define IDC_PENMAXRAD                   1008
#define IDC_PENMINRAD                   1009
#define IDC_BGMINDARK                   1010
#define IDC_PEGSHOWBG                   1011
#define IDC_PEGSHOWFG                   1012
#define IDC_AVIINFORE                   1013
#define IDC_AVIINSTART                  1014
#define IDC_AVIINSTOP                   1015
#define IDC_AVIWIDTH                    1016
#define IDC_AVIHEIGHT                   1017
#define IDC_FLIPFEW                     1018
#define IDC_RAD_DN                      1019
#define IDC_RAD_UP                      1020
#define IDC_RAD                         1021
#define IDC_DEN_DN                      1022
#define IDC_DEN                         1023
#define IDC_DEN_UP                      1024
#define IDC_TABLET_PRIMARY              1025
#define IDC_PRESSUREMAX                 1026
#define IDC_NEW_REF                     1027
#define IDC_NEW_AVI                     1028
#define IDC_NEW_USER                    1029
#define IDC_NEW_WIDTH                   1031
#define IDC_NEW_HEIGHT                  1032
#define IDC_NEW_FRAMES                  1033
#define IDC_NEW_LEVELS                  1034
#define IDC_SLD_STOP                    1035
#define IDC_NOREST                      1036
#define IDC_NAME                        1037
#define IDC_CHANGE                      1038
#define IDC_USEWINTAB                   1039
#define IDC_720x480                     1040
#define IDC_360x240                     1041
#define IDC_180x120                     1042
#define IDC_88x60                       1043
#define IDC_AUTOKEEP                    1044
#define IDC_CAP_RES                     1047
#define IDC_SCAN_SELECT                 1048
#define zIDC_LAY_MAT9                   1050
#define zIDC_LAY_MAT8                   1051
#define zIDC_LAY_MAT7                   1052
#define zIDC_LAY_MAT6                   1053
#define zIDC_LAY_MAT5                   1054
#define zIDC_LAY_MATIP                  1055
#define zIDC_LAY_MAT4                   1056
#define zIDC_LAY_MAT3                   1057
#define zIDC_LAY_MAT2                   1058
#define zIDC_LAY_MAT1                   1059
#define zIDC_LAY_MAT0                   1060
#define IDC_SPIN_LVL                    1062
#define IDC_SPIN_SKP                    1063
#define IDC_SPIN_FRM                    1064
#define IDC_SCAN_ROT0                   1065
#define IDC_SCAN_ROT90                  1066
#define IDC_SCAN_ROT180                 1067
#define IDC_SCAN_ROT270                 1068
#define IDC_SCAN_AUTO                   1069
#define IDC_RATE                        1070
#define IDC_LOOP                        1071
#define IDC_NEW_RATE                    1072
#define IDC_NEW_QTR                     1073
#define IDC_NEW_FULL                    1074
#define IDC_NEW_NTSC                    1075
#define IDC_NEW_PAL                     1076
#define IDC_NEW_HDTV                    1077
#define IDC_NEW_ACAD                    1078
#define IDC_NEW_NTSC540                 1079
#define IDC_NEW_PAL720                  1080
#define IDC_NEW_CUST                    1081
#define IDC_PREVIOUS                    1082
#define IDC_PALSCROLL                   1083
#define IDC_PALBMP                      1084
#define IDC_TOOLBOX                     1085
#define IDC_BROADCAST0                  1086
#define IDC_BROADCAST1                  1087
#define IDC_BROADCAST2                  1088
#define IDC_NOO                         1089
#define IDC_YES                         1090
#define IDC_EDIT_NS                     1091
#define IDC_EDIT_EW                     1092
#define IDC_EDIT_SC                     1093
#define IDC_EDIT_ROT                    1094
#define IDC_EDIT_BLUR                   1095
#define IDC_EDIT_ALPHA                  1096
#define IDC_EDIT_GROUP                  1097
#define IDC_START_LEVEL                 1098
#define IDC_END_LEVEL                   1099
#define IDC_START_FRAME                 1100
#define IDC_LEVEL_FLAG                  1101
#define IDC_START_FRAME2                1101
#define IDC_LEVEL_NAME                  1102
#define IDC_START_LEVEL2                1102
#define IDC_LEFTHAND                    1103
#define IDC_END_LEVEL2                  1103
#define IDC_TOOLBMP                     1104
#define IDC_RAD_VAL                     1105
#define IDC_DEN_VAL                     1106
#define IDC_CELL_NAME                   1107
#define IDC_SND_ENABLE                  1108
#define IDC_SND_WAVE                    1109
#define IDC_SND_CHANGE                  1110
#define IDC_SND_VMARK                   1111
#define IDC_SND_SMARK                   1112
#define IDC_SND_SNIP                    1113
#define IDC_NEW_STORY                   1114
#define IDC_PAL_EXTERNAL                1116
#define IDC_USE_SOUND                   1117
#define IDC_PRINT_FRAME                 1119
#define IDC_NEW_XSHEET                  1120
#define IDC_EDIT_PEG                    1121
#define IDC_IMP_ROT0                    1122
#define IDC_IMP_ROT90                   1123
#define IDC_IMP_ROT180                  1124
#define IDC_IMP_ROT270                  1125
#define IDC_IMP_24                      1126
#define IDC_ASPECT                      1128
#define IDC_WIDTH                       1129
#define IDC_CREATE                      1130
#define IDC_PLAYER                      1131
#define IDC_CHANGE_PLAYER               1132
#define IDC_PUB_NAME                    1133
#define IDC_CHANGE_NAME                 1134
#define IDC_PUB_KIND                    1135
#define IDC_BUY_IT                      1136
#define IDC_REG_IT                      1137
#define IDC_SELECT_ALL                  1138
#define IDC_CHANGE_CODEC                1146
#define IDC_CODECNAME                   1147
#define IDC_TOOL_COLOR                  1148
#define IDC_TELECINE_TEXT               1149
#define IDC_EXP_BMP                     1150
#define IDC_EXP_TGA                     1151
#define IDC_EXP_TGA32                   1152
#define IDC_EXP_CELLS                   1153
#define IDC_EXP_COMPOSITE               1154
#define IDC_EXP_COMBINE                 1155
#define IDC_NW                          1156
#define IDC_NE                          1157
#define IDC_SE                          1158
#define IDC_SW                          1159
#define IDC_PAL_IMP                     1160
#define IDC_PAL_NAME                    1161
#define IDC_KEYCODE                     1162
#define IDC_APP_MODE                    1163
#define IDC_REMIND                      1165
#define IDC_APID                        1167
#define IDC_CODE                        1168
#define IDC_INIT_REGISTER               1169
#define IDC_TEST                        1170
#define IDC_Y                           1171
#define IDC_COMBO1                      1173
#define IDC_COMPRESSORS                 1173
#define IDC_COMPUTED                    1174
#define IDC_MANUAL                      1175
#define IDC_FRAME                       1176
#define IDC_X                           1177
#define IDC_PEG_CHANGE                  1178
#define IDC_SPIN_NS                     1179
#define IDC_SPIN_EW                     1180
#define IDC_SPIN_FRAME                  1182
#define IDC_APPLY                       1184
#define IDC_PEGX                        1185
#define IDC_GROUP                       1186
#define IDC_COMBO_PEG                   1187
#define IDC_GROUP_NAME                  1188
#define IDC_PEG_NAME                    1189
#define IDC_ADJ_N                       1190
#define IDC_ADJ_S                       1191
#define IDC_ADJ_E                       1192
#define IDC_ADJ_W                       1193
#define IDC_ADJ_SC                      1194
#define IDC_ADJ_ROT                     1195
#define IDC_ADJ_BLUR                    1196
#define IDC_ADJ_ALPHA                   1197
#define IDC_ADJ_CENTER                  1198
#define IDC_PEG_CX                      1204
#define IDC_KEY_LINEAR                  1207
#define IDC_KEY_SMOOTH                  1208
#define IDC_EI_TEXT                     1209
#define IDC_EO_TEXT                     1210
#define IDC_EASEIN                      1211
#define IDC_EASEOUT                     1212
#define IDC_KEY_TYPE                    1213
#define IDC_NEXTKEY                     1214
#define IDC_CLEARKEYS                   1215
#define IDC_CAMHOME                     1216
#define IDC_CAMEND                      1217
#define IDC_CLEARALLKEYS                1218
#define IDC_PROGRESS_R                  1225
#define IDC_PROGRESS                    1226
#define IDC_LEVEL                       1228
#define IDC_HOLD                        1229
#define IDC_LABEL                       1230
#define IDC_NEW_FACT_100                1231
#define IDC_NEW_FACT_150                1232
#define IDC_NEW_FACT_200                1233
#define IDC_NEW_FACT_250                1234
#define IDC_NEW_FACT_300                1235
#define IDC_PROP_HEIGHT                 1236
#define IDC_PROP_WIDTH                  1237
#define IDC_PROP_FACTOR                 1238
#define IDC_PREVKEY                     1239
#define IDC_GOTO                        1240
#define IDC_NS                          1244
#define IDC_EW                          1245
#define IDC_XPAL_NAME                   1248
#define IDC_PAL_CHANGE                  1249
#define IDC_MDL_CHANGE                  1250
#define IDC_MDL_NAME                    1251
#define IDC_PROP_KIND                   1253
#define IDC_DETAILS                     1254
#define IDC_PRINT_PREVIEW               1256
#define IDC_PRINT_PRINT                 1258
#define IDC_PRINT_SETUP                 1259
#define IDC_PRINT_OVER                  1260
#define IDC_PRINT_DOWN                  1261
#define IDC_PRINT_SINGLE                1262
#define IDC_PRINT_LEVELS                1263
#define IDC_PRINT_FRAMES                1264
#define IDC_PRINT_LEVEL_CNT             1265
#define IDC_PRINT_FRAME_CNT             1266
#define IDC_LAYER                       1267
#define IDC_LAY_NAME                    1268
#define IDC_LAY_BLUR                    1269
#define IDC_LAY_OFFX                    1270
#define IDC_LAY_OFFY                    1271
#define IDC_LAY_SELECT                  1272
#define IDC_LAY_APPLY                   1273
#define IDC_OFFX                        1274
#define IDC_OFFY                        1275
#define IDC_BLUR                        1276
#define IDC_COLOR                       1277
#define IDC_LAY_BLURIN                  1278
#define IDC_LAY_BLURII                  1279
#define IDC_LAY_BLUROUT                 1280
#define IDC_LAY_BLURIT                  1281
#define IDC_SCAN_FIELDSIZE              1282
#define IDC_SCAN_OFFSET                 1283
#define IDC_LIGHT_DENSITY               1284
#define IDC_SCAN_VIEWLOG                1285
#define IDC_SCAN_CLEARLOG               1286
#define IDC_CK_RED                      1287
#define IDC_CK_GREEN                    1288
#define IDC_CK_BLUE                     1289
#define IDC_CK_EXTENT                   1290
#define IDC_FEAT_TELECINE               1294
#define IDC_FEAT_DESKEW                 1295
#define IDC_FEAT_HIRES                  1296
#define IDC_FEAT_COLORKEY               1297
#define IDC_LAYERS                      1298
#define IDC_PLUS                        1299
#define IDC_FEAT6                       1300
#define IDC_FEAT_CAMERA                 1301
#define IDC_PAL_SETSCENE                1303
#define IDC_PEG_SX                      1304
#define IDC_PEG_SY                      1305
#define IDC_INIT_ABOUT                  1306
#define IDC_IMP_NAME                    1307
#define IDC_INDEX                       1309
#define IDC_EXP_BAD                     1310
#define IDC_EXP_BAD2                    1311
#define IDC_SPECK1                      1312
#define IDC_SPECK2                      1313
#define IDC_SPECK3                      1314
#define IDC_SPECK4                      1315
#define IDC_SCAN_TEXT                   1316
#define IDC_SCAN_AUTOHOLD               1317
#define IDC_FRM_APPEND                  1318
#define IDC_PEN_TAB_DEN                 1319
#define IDC_CAP_FORMAT                  1320
#define IDC_CAP_SOURCE                  1321
#define IDC_CAP_DISPLAY                 1322
#define IDC_CAP_DEVICES                 1323
#define IDC_CAP_OPTIONS                 1324
#define IDC_CAP_XSHEET                  1325
#define IDC_SELECT_AUTO                 1326
#define IDC_SELECT_STAY                 1327
#define IDC_CAP_ASPECT                  1328
#define IDC_CAP_ROTATE                  1329
#define IDC_CAP_SETUP                   1331
#define IDC_SIMPLE_CURSOR               1332
#define IDC_FILL_SCROLL                 1333
#define IDC_SCAN_AUTOSCAN               1334
#define IDC_SCAN_ACCEPT                 1335
#define IDC_SCAN_BRIGHT                 1336
#define IDC_SCAN_DPI                    1337
#define IDC_SCAN_PRESCAN                1338
#define IDC_SCAN_FEEDER                 1343
#define IDC_SCAN_UI                     1344
#define IDC_SCAN_LOG                    1345
#define IDC_SCAN_TOP                    1346
#define IDC_SCAN_LEFT                   1347
#define IDC_SCAN_WIDTH                  1348
#define IDC_SCAN_HEIGHT                 1349
#define IDC_SCAN_CONTRAST               1350
#define IDC_SCAN_WINDOW                 1351
#define IDC_SCAN_T                      1352
#define IDC_SCAN_L                      1353
#define IDC_SCAN_W                      1354
#define IDC_SCAN_H                      1355
#define IDC_KEYING                      1356
#define IDC_ALPHA_KEY                   1357
#define IDC_SCAN_SAVE                   1361
#define IDC_SCAN_TEXT2                  1362
#define IDC_ENABLE_SHOW                 1364
#define IDC_NOT_AGAIN                   1365
#define IDC_PREFIX                      1368
#define IDC_PREFIX_TXT                  1369
#define IDC_CONTRAST                    1370
#define IDC_CAP_NUMBERS                 1371
#define IDC_BRIGHTNESS                  1372
#define IDC_ACCEPT                      1373
#define IDC_SCAN_FILE                   1374
#define IDC_COLOR_TYPE                  1375
#define IDC_COLOR_SIMPLE                1376
#define IDC_COLOR_GRAD                  1377
#define IDC_COLOR_PATTERN               1378
#define IDC_GRAD_SETP12                 1379
#define IDC_GRAD_SETC1                  1380
#define IDC_GRAD_SETC2                  1381
#define IDC_GRAD_SETP2                  1382
#define IDC_GRAD_COLOR                  1383
#define IDC_GRAD_CHANGE                 1384
#define IDC_KIND_CHANGE                 1385
#define IDC_DPI                         1386
#define IDC_PRODUCTS                    1387
#define IDC_LICENSEE                    1388
#define IDC_CANCEL                      1390
#define IDC_CAP_DEV_OPT                 1391
#define DEV_OPT                         1393
#define IDC_INAVI_FILE                  1394
#define IDC_LIGHT_INBETWEEN             1398
#define IDC_LIGHT_MRU                   1399
#define IDC_LIGHT_PAINT                 1400
#define IDC_LIGHT_PREV                  1401
#define IDC_LIGHT_DEPTH                 1402
#define IDC_LIGHT_BG_DARK               1403
#define IDC_LIGHT_BUD_0                 1404
#define IDC_LIGHT_BUDDY0                1405
#define IDC_LIGHT_BUD_1                 1406
#define IDC_LIGHT_BUD_2                 1407
#define IDC_LIGHT_BUD_3                 1408
#define IDC_LIGHT_BUDDY1                1409
#define IDC_LIGHT_BUDDY2                1410
#define IDC_LIGHT_BG                    1411
#define IDC_LIGTH_OPT                   1412
#define IDC_LIGHT_OPTIONS               1413
#define IDC_LIGHT_XSHEET                1414
#define IDC_PUB_AVI                     1416
#define IDC_PUB_MOV                     1417
#define IDC_PUB_GIF                     1418
#define IDC_PUB_FLV                     1419
#define IDC_GIF_OPTIONS                 1421
#define IDC_CAP_KEY_OPT                 1422
#define IDC_CAP_WHITE                   1424
#define IDC_CAP_WHITEK                  1425
#define IDC_CAP_GRAY                    1426
#define IDC_CAP_KEYED                   1427
#define IDC_CAP_WKEY                    1428
#define IDC_CK_SELECT                   1430
#define IDC_CAP_PREVIOUS                1435
#define IDC_CK_STOP                     1436
#define IDC_AVG                         1437
#define IDC_CK_RGB                      1438
#define IDC_CK_YIQ                      1439
#define IDC_CK_HLS                      1440
#define IDC_CK_LAB                      1441
#define IDC_CK_SLIDE                    1442
#define IDC_CK_INVERT                   1443
#define IDC_DEN_TEXT0                   1460
#define IDC_DEN_TEXT1                   1461
#define IDC_DEN_TEXT2                   1462
#define IDC_DEN_TEXT3                   1463
#define IDC_FILL_100                    1470
#define IDC_FILL_50                     1471
#define IDC_FILL_25                     1472
#define IDC_FILL_10                     1473
#define IDC_FILL_5                      1474
#define IDC_GIF_GRAY4                   1475
#define IDC_GIF_GRAY8                   1476
#define IDC_GIF_COLOR                   1477
#define IDC_SCAN_SCAN                   1480
#define IDC_INIT_OPEN                   1481
#define IDC_YESREST                     1482
#define IDC_FRM_DEL                     1483
#define IDC_PLAY                        1484
#define IDC_PAL_EXP                     1485
#define IDC_GRAD_SETP1                  1486
#define IDC_CT_MOVE_DN                  1487
#define IDC_PAL_EXPORT                  1488
#define ZIDC_LEVEL_PAL_IMP              1489
#define IDC_SPLASHER                    1490
#define IDC_CAP_WHTSLIDE                1491
#define IDC_FORMAT                      1492
#define IDC_SOURCE                      1493
#define IDC_CAP_GAMSLIDE                1494
#define IDC_CAP_WHTSLIDE1               1495
#define IDC_CAP_DEVICE                  1496
#define IDC_GRAB_REF                    1497
#define IDC_CAP_GAMMA                   1498
#define IDC_AVILEVEL                    1499
#define IDC_TIME                        1500
#define IDC_SIZEBOX                     1501
#define IDC_CAP_CAPTURE                 1502
#define IDC_COUNT                       1503
#define IDC_SCAN_BED                    1504
#define IDC_SCALE_BG                    1505
#define IDC_RAD_ANTI                    1506
#define ZIDC_SND_INTERNAL               1507
#define IDC_PROP_FRAMES                 1508
#define IDC_CELLLVL                     1509
#define IDC_PROP_LEVELS                 1510
#define IDC_CELLFRM                     1511
#define IDC_END_FRAME                   1512
#define IDC_END_FRAME2                  1513
#define IDC_LIGHT_BUDDY3                1514
#define IDC_PEG_CY                      1515
#define IDC_SPINZ_LVL                   1520
#define IDC_SPINZ_SKP                   1521
#define IDC_SPINZ_FRM                   1522
#define IDC_SPIN_SC                     1523
#define IDC_SPIN_ROT                    1524
#define IDC_INIT_PREV                   1525
#define IDC_PEG_FIELDCOMP               1526
#define IDC_CHECKBG                     1527
#define IDC_MDL_USE                     1528
#define IDC_LAY_DISPLAY                 1529
#define IDC_SCAN_PEGSTOP                1530
#define IDC_OUTSIDE                     1531
#define IDD_MYDIR                       1536
#define IDC_EXIT                        1537
#define IDC_RESUME                      1538
#define IDD_IMP_STATUS                  1539
#define IDC_TEXTURE                     1540
#define IDC_BRUSHBAR                    1541
#define IDC_DENSITYBAR                  1542
#define IDC_BRUSHEDIT                   1543
#define IDC_DENSITYEDIT                 1544
#define IDC_CAP_BOZO                    1560
#define IDC_CAP_WV                      1561
#define IDC_SCAN_GRAY                   1563
#define IDC_SCAN_COLOR                  1564
#define IDC_STITCH                      1565
#define IDC_CAP_SAVE                    1566
#define IDC_SAVE_SETTINGS               1567
#define IDC_CT_AVAIL                    1568
#define IDC_CT_CURRENT                  1569
#define IDC_CT_MOVE_UP                  1570
#define IDC_CT_ADD                      1571
#define IDC_CT_REMOVE                   1572
#define IDC_CT_RESET                    1573
#define IDC_LIGHT_PREV1                 1574
#define IDC_LIGHT_NEXT1                 1575
#define IDC_LIGHT_MAX                   1576
#define IDC_TRY_IT                      1577
#define IDC_EMAIL1                      1578
#define IDC_EMAIL2                      1579
#define IDC_AP_ID                       1580
#define IDC_OUR_ORDER                   1581
#define IDC_OTHER_ORDER                 1582
#define IDC_ORDER_NBR                   1583
#define IDC_HARD_ZOOM                   1584
#define IDC_OUR_TEXT                    1585
#define IDC_H_SYM                       1586
#define IDC_V_SYM                       1587
#define IDC_TEXTURE_NAME                1588
#define IDC_TEXTURE_ALPHA               1589
#define IDC_SHOW_PAINT                  1591
#define IDC_COPYRIGHT                   1592
#define IDC_CAP_WHT_TXT                 1593
#define IDC_CAP_GAM_TXT                 1594
#define ZIDC_LEVEL_PAL_EXP              1595
#define IDC_PAL_DELETE                  1596
#define IDC_PAL_PROTECTED               1597
#define IDC_PAL_LINKED                  1598
#define IDC_PAL_LINK_NAME               1599
#define IDC_PAL_IMPORT                  1600
#define IDC_PAL_DINDEX                  1602
#define IDC_PAL_NAMES                   1603
#define IDC_PAL_MAKE_SCENE              1604
#define IDC_PAL_USED                    1605
#define IDC_PAL_IF_SHARED               1606
#define IDC_SND_SLIDER                  1610
#define IDC_MIN_PRESS                   1611
#define IDC_MIN_PRESSURE                1612
#define IDC_MAX_PRESSURE                1613
#define IDC_OTHER_TEXT                  1614
#define IDC_PRINT_MARKS                 1615
#define ID_CAP_HOLD                     1616
#define IDC_FEAT_LAYERS                 1617
#define IDC_PEN_TAB_RAD                 1618
#define IDC_EXT_24                      1619
#define IDC_FILL_CHECK                  1620
#define IDC_REPEAT                      1621
#define IDC_LIGHT_NEXT                  1622
#define IDC_CAP_CROP                    1623
#define IDC_SND_INTERNALX               1624
#define IDC_LAY_ACTIVE                  1625
#define IDC_SCAN_PEGCROP                1626
#define IDC_SAVE_CACHE                  1627
#define IDC_LAY_WITHIN                  1628
#define IDC_LOCATION                    1629
#define IDC_PREVIEW                     1630
#define IDC_IMAGE                       1631
#define IDC_INIT_NEW                    1632
#define IDC_TELECINE                    1633
#define IDC_KEY                         1634
#define IDC_PAL_DEFAULT                 1635
#define IDC_PRINT_CEL                   1636
#define IDC_PEN_FREE                    1637
#define IDC_PEN_LINE                    1638
#define IDC_PEN_RECT                    1639
#define IDC_PEN_ELLIPSE                 1640
#define IDC_PEN_CURVE                   1641
#define IDC_PEN_SMART                   1642
#define IDC_TELECINEODD                 1643
#define IDC_PAL_CUSTOM                  1644
#define IDC_PRINT_XSHEET                1645
#define IDC_TELECINEEVEN                1646
#define IDC_NEW_SRATE                   1647
#define IDC_PAL_SCENE                   1648
#define IDC_HEIGHT                      1649
#define IDC_NEW_SFRAMES                 1650
#define IDC_FRM_INS                     1652
#define IDC_VFLIP                       1657
#define IDC_HFLIP                       1658
#define IDC_LEVEL_PAL                   1660
#define IDC_PAL_SEL                     1661
#define IDC_EXP_COMBO                   1662
#define IDC_PEG_GROUP                   1663
#define IDC_COMBO_GROUP                 1664
#define IDC_PEGS                        1665
#define IDC_PEG                         1666
#define IDC_ABT_AVAIL_VIRT              1667
#define IDC_ABT_TOTAL_VIRT              1668
#define IDC_ABT_AVAIL_RAM               1669
#define IDC_ABT_TOTAL_RAM               1670
#define IDC_ABT_SPEED                   1671
#define IDC_ABT_LOAD                    1672
#define IDC_ABT_OS                      1673
#define IDC_PAL_CLONE                   1675
#define IDC_CT_APPLY                    1676
#define IDC_CD_WHEEL                    1677
#define IDC_CD_SLIDER                   1678
#define IDC_CD_SIMPLE                   1679
#define IDC_CD_GRAD                     1680
#define IDC_CD_TEXTURE                  1681
#define IDC_CD_TEXT_H                   1682
#define IDC_CD_TEXT_V                   1683
#define IDC_CD_TEXT_ALPHA               1684
#define IDC_CD_TEXT_NAME                1685
#define IDC_CD_HSL                      1686
#define IDC_CD_HSV                      1687
#define IDC_CD_R                        1688
#define IDC_CD_G                        1689
#define IDC_CD_B                        1690
#define IDC_CD_GRAD_C1                  1694
#define IDC_CD_GRAD_C2                  1695
#define IDC_CD_GRAD_RAD                 1696
#define IDC_CD_GRAD_LIN                 1697
#define IDC_CD_GRAD_P1                  1698
#define IDC_CD_GRAD_P2                  1699
#define IDC_CD_GRAD_PP                  1700
#define IDC_CD_COLOR                    1701
#define IDC_CD_TEXT_CHANGE              1702
#define IDC_CD_OPACITY                  1703
#define IDC_CD_SLIDE_TEXT               1704
#define IDC_CD_RED                      1705
#define IDC_CD_GREEN                    1706
#define IDC_CD_BLUE                     1707
#define IDC_CD_HUE                      1708
#define IDC_CD_SAT                      1709
#define IDC_CD_LUM                      1710
#define IDC_CD_OPAC                     1711
#define IDC_CD_TXT_NAME                 1712
#define IDC_CD_REVERT                   1713
#define IDC_SLD_START                   1713
#define IDC_SLD_SLIDER                  1714
#define IDC_SLD_VOLUME                  1715
#define IDC_SLD_RATE                    1716
#define IDC_SLD_FRAME                   1717
#define IDC_SLD_PLAY                    1721
#define IDC_SLD_FWD                     1722
#define IDC_SLD_END                     1723
#define IDC_SLD_BACK                    1724
#define IDC_BUTTON8                     1725
#define IDC_SLD_BEGIN                   1725
#define IDC_CAM_NONE                    1725
#define IDC_SLD_LOOP                    1726
#define IDC_SLD_FPS                     1727
#define IDC_SLD_VOLTXT                  1728
#define IDC_SND_TRACK                   1729
#define IDC_QUAL_TEXT                   1730
#define IDC_USE_JPEG                    1731
#define IDC_QUALITY                     1732
#define IDC_NEW_PREV1                   1733
#define IDC_NEW_PREV2                   1734
#define IDC_NEW_PREV3                   1735
#define IDC_NEW_PREV4                   1736
#define IDC_NEW_JPEG                    1737
#define IDC_NEW_QUALITY                 1738
#define IDC_NEW_QUALTEXT                1739
#define IDC_SEL_PAL                     1740
#define IDC_PAL_MOD_ALL                 1741
#define IDC_PAL_MOD_ONE                 1742
#define IDC_PAL_NEW_TEXT                1743
#define IDC_PAL_NEW_NAME                1744
#define IDC_PAL_EXT_NAME                1745
#define IDC_PAL_EXT_FNAME               1745
#define IDC_PAL_EXT_UPDATE              1746
#define IDC_PAL_EXT_NEW                 1747
#define IDC_PAL_FNAME                   1748
#define IDC_PAL_NO                      1749
#define IDC_PAL_EXT_NAME_TEXT           1752
#define IDC_PAL_EXT_NAM                 1753
#define IDC_CD_GRAD_OR                  1756
#define IDC_CD_GRAD_AND                 1757
#define IDC_CHK_UPDATES                 1758
#define IDC_PAL_EXT_LOCATE              1759
#define IDC_PAL_EXT_NO_LOCATE           1760
#define IDC_MISSING_TEXTURE             1761
#define IDC_TEXTURE_LOCATE              1762
#define IDC_TEXTURE_REVERT              1763
#define IDC_AVI_TRACK0                  1764
#define IDC_AVI_TRACK1                  1765
#define IDC_AVI_TRACK2                  1766
#define IDC_AVI_TRACK3                  1767
#define IDC_GRAD_RAD                    1768
#define IDC_GRAD_LIN                    1769
#define IDC_SHEET_TOP                   1771
#define IDC_PEN_RAD                     1780
#define IDC_PEN_DEN                     1781
#define IDC_PEN_HALO                    1782
#define IDC_PEN_RAD_TXT                 1785
#define IDC_PEN_DEN_TXT                 1786
#define IDC_PEN_HALO_TXT                1787
#define IDC_PEN_RAMP0                   1790
#define IDC_PEN_RAMP1                   1791
#define IDC_PEN_RAMP2                   1792
#define IDC_PEN_RAMP3                   1793
#define IDC_PEN_PICT                    1799
#define IDC_LEFT_SCROLL                 1800
#define IDC_NO_LICENSE                  1801
#define ID_KEY_TOOL_TYPE                1802
#define ID_TOOL_ERASER_BOX              1803
#define IDC_IMP_DRAWING                 1804
#define IDC_IMP_COLOR                   1805
#define IDC_CT_REVERT                   1807
#define IDC_LIGHTBOX_PAINT              1808
#define IDC_LIGHT_TOOL                  1809
#define IDC_USE_MOUTHS                  1810
#define IDC_CAP_AUTO                    1811
#define IDC_REC_RECORD                  1812
#define IDC_REC_PLAY                    1813
#define IDC_REC_STOP                    1814
#define IDC_REC_IMPORT                  1815
#define IDC_REC_VID_DEV                 1817
#define IDC_REC_AUD_DEV                 1818
#define IDC_REC_AUD_TXT                 1819
#define IDC_REC_SETTINGS                1820
#define IDC_BUTTON1                     1822
#define IDC_PUB_FLV2                    1822
#define IDC_CAM_ALL                     1822
#define IDC_IMPORT                      1822
#define IDC_FROM_AVI                    1822
#define IDC_FEAT_PLUS                   1823
#define IDC_SCRUB_EDIT                  1824
#define IDC_PUCK                        1825
#define IDC_PUCK_1                      1826
#define IDC_PUCK_2                      1827
#define IDC_ZOOM_FIT                    1828
#define IDC_ZOOM_100                    1829
#define IDC_ZOOM_HAND                   1830
#define IDC_ZOOM_ZOOM                   1831
#define IDC_ZOOM_ZOOMER                 1832
#define IDC_EDIT1                       1833
#define IDC_PROP_ID                     1833
#define IDC_COLUMNS                     1833
#define IDC_EMBED_NAME                  1833
#define IDC_REC_DELAY                   1833
#define IDC_FREEFORM                    1835
#define IDC_MANIPULATE                  1836
#define IDC_AUTO_LOAD                   1837
#define IDC_FEAT_LIBRARY                1838
#define IDC_LIB_NAME                    1839
#define IDC_LIB_PALETTE                 1840
#define IDC_LIB_GRID                    1842
#define IDC_CAM_X                       1842
#define IDC_SET_NAME                    1843
#define IDC_CAM_Y                       1844
#define IDC_CAM_Z                       1845
#define IDC_CAM_R                       1846
#define IDC_CAM_B                       1847
#define IDC_CAM_A                       1848
#define IDC_CAM_COMPUTED                1849
#define IDC_CAM_GROUPS                  1850
#define IDC_CAM_LIST                    1851
#define IDC_CAM_IMP_RANGE               1852
#define IDC_CAM_IMP_FRAME               1853
#define IDC_CAM_IMP_LEVEL               1854
#define IDC_CAM_ONLY_ACTIVE             1855
#define IDC_CAM_IMP_GROUP               1856
#define IDC_CHECK1                      1857
#define IDC_SELECT_LASSO                1857
#define IDC_AVI_SCALE                   1857
#define IDC_EMBED_TRIM                  1857
#define IDC_AVI_RATE_ADJ                1857
#define IDC_ERASE_CAP_FILE              1857
#define IDC_PLAYBACK                    1857
#define IDC_LEVEL_HOLD                  1857
#define IDC_EMBED_SND_BOX               1858
#define IDC_EMBED_SND_NEVER             1859
#define IDC_EMBED_SND_ALWAYS            1860
#define IDC_EMBED_SND_PROMPT            1861
#define IDC_FEAT_PLUSX                  1862
#define IDC_EXP_EMBED                   1864
#define IDC_REC_LOOPER                  1865
#define IDC_STARTUP                     1866
#define IDC_EMB_IN_NEVER                1867
#define IDC_EMB_IN_ALWAYS               1868
#define IDC_EMBED_IN_PROMPT             1869
#define IDC_EMB_OUT_NEVER               1870
#define IDC_EMB_OUT_ALWAYS              1871
#define IDC_EMB_OUT_PROMPT              1872
#define IDC_MASTER_NONE                 1873
#define IDC_MASTER_VIDEO                1874
#define IDC_MASTER_AUDIO                1875
#define IDC_RATE_SCENE                  1876
#define IDC_RATE_VIDEO                  1877
#define IDC_USE_FRAMES                  1878
#define IDC_AVI_NO_SCALE                1880
#define IDC_AVI_ASPECT_HOLD             1882
#define IDC_AVI_RATE_NONE               1883
#define IDC_AVI_RATE_SCENE              1884
#define IDC_AVI_RATE_ADJUST             1885
#define ZIDC_LR                         1885
#define IDC_AVI_TEMPORAL                1886
#define IDC_AVI_SPATIAL                 1887
#define IDC_AVI_SCALE_IT                1888
#define IDC_AVI_AUDIO                   1889
#define IDC_REC_SIZE                    1891
#define IDC_MSG                         1892
#define IDC_NOW                         1893
#define IDC_PUBLISH                     1894
#define IDC_START_AT_0                  1895
#define IDC_START_AT_1                  1896
#define IDC_UL                          1897
#define IDC_UR                          1898
#define IDC_LL                          1899
#define IDC_LR                          1900
#define IDC_AVI_MSG1                    1900
#define IDC_AVI_MSG2                    1901
#define IDC_EMB_OVERRIDE                1902
#define IDC_APP_EXPIRES                 1903
#define IDC_APP_EXP_DATE                1904
#define ID_VIEW_LIB_0                   2970
#define ID_LIB_UNLOAD_0                 2980
#define ID_LIB_LOAD                     2990
#define ID_LIB_SAVE                     2991
#define ID_LIB_UNLOAD                   2992
#define ID_FILE_EXPORT_CAM              2993
#define ID_FILE_IMPORT_CAM              2994
#define ID_FILE_EXPORT_PAL              2995
#define ID_FILE_IMPORT_PAL              2996
#define ID_FILE_IMPORT_MAYA             2997
#define ID_FILE_REVERT                  2998
#define ID_FILE_SAVEAS_MODEL            2999
#define ID_FILE_IMPAVI                  3000
#define ID_FILE_EXPORT_EMB              3001
#define IDC_RENEW_IT                    9998
#define OPTPLAYER                       9999
#define FIRST_OPTION                    10000
#define WINTAB                          10001
#define BGMIN                           10002
#define PEG_SHOWBG                      10003
#define PEG_SHOWFG                      10004
#define PEG_DEPTH                       10005
#define PEG_DENSITY                     10006
#define PEN_MINRAD                      10007
#define PEN_MAXRAD                      10008
#define PNC_MINDEN                      10009
#define PNC_MAXDEN                      10010
#define ERS_MINDEN                      10011
#define ERS_MAXDEN                      10012
#define SHT_SHOWBG                      10013
#define FLIP_FEW                        10014
#define TAB_PRIMARY                     10015
#define MAX_PRESSURE                    10016
#define AUTOKEEP                        10017
#define LOOPPLAY                        10018
#define DEF_WIDTH                       10019
#define DEF_HEIGHT                      10020
#define DEF_FRAMES                      10021
#define DEF_RATE                        10022
#define DEF_KIND                        10023
#define DEF_LEVELS                      10024
#define XSHEET_HIGHLIGHT                10025
#define LEFTHAND                        10026
#define SHOWTHUMBS                      10027
#define CAPTURE_DEVICE                  10028
#define VIDCAP_X                        10029
#define VIDCAP_Y                        10030
#define VIDCAP_OPTS                     10031
#define VIDCAP_WHITE                    10032
#define VIDCAP_GAMMA                    10033
#define DEF_HOLD                        10034
#define TOOLSAME                        10035
#define DEF_FACTOR                      10036
#define CHECKERBG                       10037
#define SCANROTATE                      10038
#define PRINTOPTS                       10039
#define XSCALE_BG                       10040
#define VIDCAP_RED                      10041
#define VIDCAP_GREEN                    10042
#define VIDCAP_BLUE                     10043
#define VIDCAP_EXTENT                   10044
#define SCAN_FIELD                      10045
#define SCAN_OFFSET                     10046
#define SCAN_PEGTOP                     10047
#define SCAN_CROPPEG                    10048
#define VIDCAP_WIDTH                    10049
#define VIDCAP_HEIGHT                   10050
#define SELECT_FLAGS                    10051
#define SIMPLE_CURSOR                   10052
#define EXTEDIT_OPTS                    10053
#define HARD_ZOOM                       10054
#define SC_SOUND                        10055
#define SC_QUIET                        10056
#define SC_SNIP                         10057
#define SC_BLIND                        10058
#define SC_SCACHE                       10059
#define SC_TELECINE                     10060
#define SC_MRU                          10061
#define SC_NEXT                         10062
#define SC_PREV                         10063
#define SC_NEXT1                        10064
#define SC_PREV1                        10065
#define SC_PAINT                        10066
#define JPEG_QUAL                       10067
#define DEF_PREVIEW                     10068
#define DEF_BROADCAST                   10069
#define MIN_PRESSURE                    10070
#define TABLET_USED                     10071
#define LEFT_SCROLL                     10072
#define SC_LIGHT_PAINT                  10073
#define USE_MOUTHS                      10074
#define EDIT_SCRUB                      10075
#define SC_EMBED_OUT                    10076
#define SC_EMBED_IN                     10077
#define SC_EMBED_TRIM                   10078
#define REC_FILE                        10079
#define REC_VNAME                       10080
#define REC_ANAME                       10081
#define REC_CNAME                       10082
#define REC_CAP_VID                     10083
#define REC_CAP_AUD                     10084
#define REC_CAP_CC                      10085
#define REC_PREVIEW                     10086
#define REC_SIZE                        10087
#define REC_ERASE                       10088
#define REC_TIME                        10089
#define ZREC_MASTER                     10090
#define REC_DELAY                       10091
#define RECORD_X                        10092
#define RECORD_Y                        10093
#define SC_AVI_SCALE                    10094
#define REC_GUID                        10095
#define SC_APPLY_FRAME                  10096
#define OVERRIDE_FLAGS                  10097
#define LAST_OPTION                     10098
#define IDS_TEMPNOW                     10120
#define IDS_DIFF2_USB                   10123
#define IDS_REVERT_DEMO                 10124
#define IDS_NO_USB                      10125
#define IDS_DIFF_USB                    10126
#define IDS_NO_HELP                     10127
#define IDS_EXPORT_EMBED                10128
#define IDS_SAVE_MODEL                  10129
#define IDS_LOAD_MODEL                  10130
#define IDS_CREATE_NEW                  10133
#define IDS_EXPORTAVI                   10134
#define IDS_EXPORTBMP                   10135
#define IDS_SELECTPLAY                  10136
#define IDS_SELECTAVI                   10137
#define IDS_PAL_IMPORT                  10138
#define IDS_PAL_EXPORT                  10139
#define IDS_NS_KEY                      10140
#define IDS_EW_KEY                      10141
#define IDS_SCALE_KEY                   10142
#define IDS_ROTATE_KEY                  10143
#define IDS_BLUR_KEY                    10144
#define IDS_ALPHA_KEY                   10145
#define IDS_EXPORTGIF                   10146
#define IDS_EXPORT_MOVIE                10147
#define IDS_EMAIL_BAD                   10148
#define IDS_EMAIL_MISMATCH              10149
#define IDS_NO_EMAIL                    10150
#define IDS_NO_NAME                     10151
#define IDS_NO_ID                       10152
#define IDS_NO_ORDER                    10153
#define IDS_CLOSING                     10154
#define IDS_EXTRACTWAV                  10155
#define IDS_PAL_IMP_LITE                10156
#define IDS_PAL_READ_LITE               10157
#define IDS_NO_INI_WRITE                10158
#define IDS_EXPORT_FLV                  10159
#define IDS_EXPORT_LIBRARY              10160
#define IDS_IMPORT_LIBRARY              10161
#define IDS_EXPORT_CAMERA               10162
#define IDS_IMPORT_CAMERA               10163
#define ID_ACTION_FILL                  10900
#define ID_LIP_DEFAULT                  10998
#define ID_LIP_SCENE                    10999
#define ID_TOOL_PENCIL                  11000
#define ID_TOOL_TRACE                   11001
#define ID_TOOL_BRUSH                   11002
#define ID_TOOL_FILL                    11003
#define ID_TOOL_ZOOM                    11004
#define ID_TOOL_HAND                    11005
#define ID_TOOL_EYEDROP                 11006
#define ID_TOOL_ERASER                  11007
#define ID_TOOL_SELECT                  11008
#define ID_TOOL_WAND                    11009
#define ID_TOOL_CURVE                   11010
#define ID_TOOL_LINE                    11011
#define ID_TOOL_FREE                    11012
#define ID_TOOL_CAM_SELECT              11020
#define ID_TOOL_CAM_PAN                 11021
#define ID_TOOL_CAM_ZOOM                11022
#define ID_TOOL_CAM_ROTATE              11023
#define ID_TOOL_CAM_BLUR                11024
#define ID_TOOL_CAM_ALPHA               11025
#define ID_TOOL_CAM_DALL                11026
#define ID_TOOL_CAM_DTHIS               11027
#define ID_TOOL_CAM_NEXT                11028
#define ID_TOOL_CAM_PREV                11029
#define ID_TOOL_CAM_DLG                 11035
#define IDS_TOO_BIG_AVI                 19998
#define IDS_NO_SOUND                    19999
#define IDS_NO_WAVE                     20000
#define IDS_BIG_AVI                     20001
#define IDS_OLD_VFW                     20002
#define IDS_BAD_WRITE                   20003
#define IDS_BAD_TWAIN                   20004
#define IDS_CAP_CONNECT                 20005
#define IDS_TWAIN_ERROR                 20006
#define IDS_VID_CAP                     20007
#define IDS_SCENE_CREATE                20008
#define IDS_SCENE_LOAD                  20009
#define IDS_SCENE_SAVE                  20010
#define IDS_FILE_CREATE                 20011
#define IDS_FILE_OPEN                   20012
#define IDS_FILE_READ                   20013
#define IDS_SCENE_SAVE1                 20014
#define IDS_SCENE_SAVE2                 20015
#define IDS_REGISTER1                   20016
#define IDS_REGISTER2                   20017
#define IDS_DEMO_WARNING                20018
#define IDS_AREYOUSURE                  20019
#define IDS_NOTLITE                     20020
#define IDS_NOTPT                       20021
#define IDS_DEMO                        20022
#define IDS_STANDARD                    20023
#define IDS_LITE                        20024
#define IDS_PT                          20025
#define IDS_PRO                         20026
#define IDS_NOTSTD                      20027
#define IDS_NOMEMORY                    20028
#define IDS_NOWINTAB                    20029
#define IDS_TOO_MANY_FRAMES             20030
#define IDS_TOO_MANY_LEVELS             20031
#define IDS_NOT_HIRES                   20032
#define IDS_MAX_FRAMES                  20033
#define IDS_REGISTER3                   20034
#define IDS_REGISTER4                   20035
#define IDS_REGISTER5                   20036
#define IDS_REGISTER6                   20037
#define IDS_SCENE_NEWER                 20040
#define IDS_NO_TABLET                   20050
#define IDS_WIDE_PASTE                  20100
#define ID_PREVIEW_1                    22600
#define ID_PREVIEW_2                    22601
#define ID_PREVIEW_3                    22602
#define ID_PREVIEW_4                    22603
#define ID_KEY_F1                       22701
#define ID_KEY_F2                       22702
#define ID_KEY_F3                       22703
#define ID_KEY_F4                       22704
#define ID_KEY_F5                       22705
#define ID_KEY_F6                       22706
#define ID_KEY_F7                       22707
#define ID_KEY_F8                       22708
#define ID_KEY_F9                       22709
#define ID_KEY_F10                      22710
#define ID_KEY_F11                      22711
#define ID_KEY_F12                      22712
#define ID_KEY_SF9                      22723
#define ID_KEY_SF10                     22724
#define ID_KEY_SF11                     22725
#define ID_KEY_SF12                     22726
#define ID_KEY_CF9                      22739
#define ID_KEY_CF10                     22740
#define ID_KEY_CF11                     22741
#define ID_KEY_CF12                     22742
#define ID_CAP_ROTATE                   22760
#define ID_CAP_NUMBERS                  22761
#define ID_CAP_BOZO                     22762
#define ID_CAP_F9                       22763
#define ID_CAP_OVERLAY                  22764
#define ID_VIEW_CAM_TOOLS               22779
#define ID_VIEW_SHEET                   22780
#define ID_VIEW_FLIP                    22781
#define ID_VIEW_PALETTE                 22782
#define ID_VIEW_VCR                     22783
#define ID_KEY_UP                       22784
#define ID_KEY_DOWN                     22785
#define ID_VIEW_MODE                    22786
#define ID_OPTIONS                      22787
#define ID_VIEW_TOOLS                   22788
#define ID_KEY_LEFT                     22789
#define ID_KEY_RIGHT                    22790
#define ID_OPT_SETTING                  22791
#define ID_OPT_FG                       22792
#define ID_OPT_BG                       22793
#define ID_FILE_EXPAVI                  22794
#define ID_FILE_SCAN                    22795
#define IDD_FILE_EXPORT                 22796
#define ID_FILE_PUBLISH                 22797
#define ID_FILE_EXPSWF                  22798
#define ID_OPT_SOUND                    22799
#define ID_OPT_KEEP                     22800
#define ID_KEY_ENTER                    22801
#define ID_KEY_BACK                     22802
#define ID_KEY_SPACE                    22803
#define ID_EDIT_REVERT                  22804
#define ID_FILE_CAPTURE                 22805
#define ID_TIMER_FIRE                   22806
#define ID_TOOL_INTENSITY               22807
#define ID_TOOL_RADIUS                  22808
#define ID_TOOL_SCAN                    22809
#define ID_TOOL_CAPTURE                 22810
#define ID_FILE_GRAB                    22812
#define ID_FILE_RECORD                  22813
#define ID_EDIT_INS                     22814
#define ID_EDIT_DEL                     22815
#define ID_EDIT_BLANK                   22816
#define ID_EDIT_CLEARC                  22817
#define ID_OPT_SHOWTHUMBS               22818
#define ID_VIEW_SOUND                   22819
#define ID_FILE_CVTSTRYBRD              22820
#define ID_FILE_EXPORT                  22821
#define ID_OPT_AUTOCOMP                 22822
#define ID_FILE_IMPFILE                 22823
#define ID_APP_HELP                     22824
#define ID_MY_PAINT                     22825
#define ID_ZOOM_25                      22826
#define ID_ZOOM_50                      22827
#define ID_ZOOM_100                     22828
#define ID_ZOOM_200                     22829
#define ID_ZOOM_300                     22830
#define ID_ZOOM_400                     22831
#define ID_ZOOM_800                     22832
#define ID_APP_REGISTER                 22833
#define ID_EDIT_PASTEREVERSED           22834
#define ID_VIEW_CAMERA                  22835
#define ID_KEY_CLEFT                    22836
#define ID_KEY_CRIGHT                   22837
#define ID_KEY_CUP                      22838
#define ID_KEY_CDOWN                    22839
#define ID_ACTION_FLIP                  22840
#define ID_APP_PROPERTIES               22841
#define ID_VIEW_CAMERA_100              22842
#define ID_VIEW_CAMERA_50               22843
#define ID_VIEW_CAMERA_25               22844
#define ID_VIEW_CAMERA_ENLARGE          22845
#define ID_VIEW_CAMERA_GRID             22846
#define ID_EDIT_MAKEMODEL               22847
#define ID_EDIT_MODEL                   22848
#define ID_FILE_IMPWAVE                 22849
#define ID_VIEW_LAYER                   22850
#define ID_VIEW_LAY_UP                  22851
#define ID_VIEW_LAY_DN                  22852
#define ID_VIEW_CAMERA_CENTER           22853
#define ID_ACTION_MATTE                 22854
#define ID_VIEW_VIDEO                   22855
#define ID_VCR_SLIDER_STOP              22856
#define ID_ACTION_SPECK                 22857
#define ID_VIEW_VIDEOWINDOW             22858
#define ID_VIEW_VIDEO2                  22859
#define ID_SLIDER_START                 22860
#define ID_SLIDER_STOP                  22861
#define ID_CAP_SCALEFIT                 22862
#define ID_EDIT_APPEND                  22863
#define ID_VIEW_FULL                    22864
#define ID_FILE_EDIT                    22865
#define ID_EDIT_OUTSIDE                 22866
#define ID_VIEW_LIPSYNC                 22869
#define ID_CAP_XSHEET                   22870
#define ID_CAP_WV                       22871
#define ID_FILE_IMPMOV                  22873
#define ID_VIEW_TIMING                  22874
#define ID_OPT_LIGHTBOX                 22876
#define ID_OPT_CUST_TB                  22877
#define ID_KEY_PGUP                     22878
#define ID_KEY_PGDN                     22879
#define ID_KEY_HOME                     22880
#define ID_KEY_END                      22881
#define ID_EXPORT_MAYA                  22882
#define ID_VIEW_SUBPAL                  22883
#define ID_MAGIC_11                     22884
#define ID_MAGIC_12                     22885
#define IDD_ABOUTBOX2                   22886
#define IDD_WARNING1                    22887
#define IDD_WARNING2                    22888
#define IDD_WARNING3                    22889
#define IDD_REGISTER1                   22890
#define IDD_REGISTER2                   22891
#define IDD_REGISTER3                   22892
#define IDD_REGISTER4                   22893
#define IDD_REGISTER5                   22894
#define IDD_REGISTER6                   22895
#define IDD_REGISTER7                   22896
#define IDD_DEMO_DISC                   22897
#define ID_MY_PERFORM                   22898
#define IDD_RECORD                      22898
#define ID_MY_EXIT                      22899
#define IDD_RECOPT                      22899
#define ID_FRAME_ENTER_KEY              22900
#define ID_ZOOM_33                      22901
#define ID_APP_UPDATES                  22902
#define ID_EDIT_CLEAR_SEL               22903
#define ID_ZOOM_FIT                     22904
#define ID_FILE_RECORDER                22905
#define ID_VIEW_PUCK                    22906
#define ID_VIEW_ZOOMER                  22907
#define IDC_EMBED_LIST                  22909
#define ID_OPT_EMBEDDED                 22910
#define IDC_SLD_RECORD                  22911
#define IDC_DO_VIDEO                    22912
#define IDC_VID_DIALOGS                 22913
#define IDC_VID_DEV_TXT                 22914
#define IDC_DO_AUDIO                    22915
#define IDC_AUD_DIALOGS                 22916
#define IDC_AUD_DLG_TXT                 22917
#define IDC_VID_DLG_TXT                 22918
#define IDC_AUD_DEV_TXT                 22919
#define IDC_SLD_FRAMES                  22920
#define IDC_SETTINGS                    22921
#define IDC_FRAME_RATE                  22923
#define IDC_TIME_LIMIT                  22924
#define IDC_CAP_EXPORT                  22925
#define IDC_STATUS                      22926
#define ID_OPT_FRAME_NBR                22927
#define ID_OPT_ICON_LARGE               22928
#define ID_OPT_ICON_MED                 22929
#define ID_OPT_ICON_SMALL               22930
#define ID_OPT_ICON_TINY                22931
#define ID_OPT_OVERRIDE_HOLD            22932
#define ID_OPT_OVERRIDE_SCRUB           22933
#define ID_OPT_OVERRIDE_EMBED           22934
#define IDS_NOT_FOR_LITE                27340
#define IDS_UPDATE_NOW                  27341
#define IDS_CHECK_INTERNET              27342
#define IDS_NO_DIGICEL_CONNECT          27343
#define IDS_VERSION_UP_TO_DATE          27344
#define IDS_VERSION_OUT_OF_DATE         27345
#define IDS_PROMPT_KEEP_FRAME           27346
#define IDS_NOPLAYER                    27347
#define IDS_CELL_OPENED                 27348
#define IDS_PROMPT_KEEP_CLIP            27349
#define IDS_NO_PASTE                    27350
#define IDS_NO_PASTE_RES                27351
#define IDS_PROMPT_KEEP_MODEL           27352
#define IDS_EXT_PALS                    27353
#define IDS_EXT_PALDIFF                 27354
#define IDS_EXT_MODEL                   27355
#define IDS_EXT_WAVE                    27356
#define IDS_EXT_CHECK                   27357
#define IDS_PALETTE_SCENE               27358
#define IDS_PALETTE_EXTERNAL            27359
#define IDS_PALETTE_DEFAULT             27360
#define IDS_NO_LICENSEMGR               27362
#define IDS_NO_CLIENT                   27363
#define IDS_NO_RENEW                    27364
#define IDS_EDUCATIONAL                 27365
#define IDS_PALETTE_PROTECTED           27366
#define IDS_PALETTE_LOCKED              27367
#define IDS_NO_TEXTURE_FILE             27368
#define IDS_NO_LIC_PRODUCTS             27369
#define IDS_EXT_SND_LEVELS              27370
#define IDS_EXT_WAVE_CHANGE             27371
#define IDS_USING_OVERLAY               27372
#define IDS_EXT_MODEL_CHANGE            27373
#define IDS_EXT_PAL_CHANGE              27374
#define IDS_EXT_TEXTURE_CHANGE          27375
#define IDS_NO_CUT_EDIT                 27376
#define IDS_LIB_NO_BG                   27377
#define IDS_LIB_LOAD                    27378
#define IDS_NO_WORK                     27379
#define IDS_NO_CREATE                   27380
#define IDS_ERR_QT_INIT                 27381
#define IDS_ERR_MAYA_INIT               27383
#define IDS_ERR_MAYA_CLOSE              27384
#define IDS_ERR_FILE_READ               27385
#define IDS_ERR_LIB_SAVE                27386
#define IDS_ERR_INI_COPY                27387
#define IDS_ERR_SCAN_SAVE               27388
#define IDS_ERR_LICENSE_UNLOCK          27389
#define IDS_ERR_BAD_MOUTH               27390
#define IDS_ERR_FLV_CREATE              27391
#define IDS_ERR_FLV_CONVERT             27392
#define IDS_ERR_FLV_ERROR               27393
#define IDS_ERR_PROG2                   27394
#define IDS_ERR_NO_OPEN                 27395
#define IDS_CUT_WARNING                 27396
#define IDS_AVI_IMPORT                  27397
#define IDS_FRAME_COUNT_EXCEEDED        27398
#define IDS_AVIDLG_FASTER               27399
#define IDS_AVIDLG_SLOWER               27400
#define IDS_AVIDLG_DROP                 27401
#define IDS_AVIDLG_ADD                  27402
#define IDS_AVIDLG_SMALLER              27403
#define IDS_AVIDLG_LARGER               27404
#define IDS_AVIDLG_GRAY                 27405
#define IDS_CLEARALL                    61203

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        537
#define _APS_NEXT_COMMAND_VALUE         22935
#define _APS_NEXT_CONTROL_VALUE         1905
#define _APS_NEXT_SYMED_VALUE           243
#endif
#endif
